default_platform(:ios)

platform :ios do
  desc "TestFlightにアップロード"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    increment_build_number(xcodeproj: "copyPaste.xcodeproj")

    build_app(
      scheme: "copyPaste",
      export_method: "app-store"
    )

    upload_to_testflight(api_key: api_key)
  end

  desc "App Storeに申請"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"]
    )

    upload_to_app_store(
      api_key: api_key,
      submit_for_review: true,
      automatic_release: false,
      force: true,
      skip_binary_upload: true,
      precheck_include_in_app_purchases: false,
      metadata_path: "fastlane/metadata",
      screenshots_path: "fastlane/screenshots"
    )
  end
end
